CRITICAL - 2024-07-20 10:10:10 --> ErrorException: Undefined array key "image"
[Method: GET, Route: cake_catalog]
in APPPATH\Views\cake_catalog.php on line 11.
 1 APPPATH\Views\cake_catalog.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "image"', 'D:\\xampp\\htdocs\\benoite\\app\\Views\\cake_catalog.php', 11)
 2 SYSTEMPATH\View\View.php(234): include('D:\\xampp\\htdocs\\benoite\\app\\Views\\cake_catalog.php')
 3 SYSTEMPATH\View\View.php(237): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1171): CodeIgniter\View\View->render('cake_catalog', [], true)
 5 APPPATH\Controllers\Home.php(19): view('cake_catalog', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->cake_catalog()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('D:\\xampp\\htdocs\\benoite\\public\\index.php')
ERROR - 2024-07-20 10:53:13 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-07-20 11:02:29 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-07-20 11:05:10 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
ERROR - 2024-07-20 11:38:48 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\xampp\htdocs\benoite\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\xampp\htdocs\benoite\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\xampp\htdocs\benoite\system\Database\BaseBuilder.php(2332): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\xampp\htdocs\benoite\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\xampp\htdocs\benoite\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\xampp\htdocs\benoite\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\xampp\htdocs\benoite\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\xampp\htdocs\benoite\app\Controllers\Auth.php(22): CodeIgniter\BaseModel->save(Array)
#9 D:\xampp\htdocs\benoite\system\CodeIgniter.php(933): App\Controllers\Auth->store()
#10 D:\xampp\htdocs\benoite\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 D:\xampp\htdocs\benoite\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\benoite\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\xampp\htdocs\benoite\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\xampp\htdocs\benoite\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\xampp\htdocs\benoite\system\rewrite.php(44): require_once('D:\\xampp\\htdocs...')
#16 {main}
